import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions — Korrali ThreadExtract",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/40 bg-background/80 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 h-16">
          <Link href="/" className="flex items-center gap-2.5 font-semibold">
            <span className="inline-grid h-8 w-8 place-items-center rounded-md bg-gradient-to-b from-[#10b981] to-[#3b82f6] text-sm font-bold text-white">K</span>
            <span className="text-base">Korrali ThreadExtract</span>
          </Link>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-extrabold text-foreground mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: August 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:mb-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_strong]:text-foreground">

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By installing, accessing, or using Korrali ThreadExtract (&quot;the Service&quot;), you agree to
              these Terms &amp; Conditions. If you do not agree, do not use the Service. If you are
              installing the Service on behalf of an organization, you represent that you have authority to
              bind that organization to these terms.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              ThreadExtract is a Slack app that, upon a 🧠 emoji reaction to a thread, retrieves that
              thread&apos;s messages via the Slack API, generates an AI summary, and publishes it as a page
              to a Notion database you connect.
            </p>
          </section>

          <section>
            <h2>3. Account Registration</h2>
            <p>
              You must sign in via Google or a magic-link email to access the dashboard and manage billing.
              You are responsible for maintaining the confidentiality of your account access.
            </p>
          </section>

          <section>
            <h2>4. Subscription Plans &amp; Billing</h2>
            <ul>
              <li>ThreadExtract is offered on Free, Pro, and Team tiers, described on our pricing page.</li>
              <li>New workspace installs receive a 14-day trial; afterward, continued use of paid features requires an active subscription.</li>
              <li>Paid subscriptions are billed through Stripe on a recurring basis until cancelled.</li>
              <li>You may cancel at any time from the billing page; cancellation takes effect at the end of the current billing period. Fees already paid are non-refundable except where required by law.</li>
            </ul>
          </section>

          <section>
            <h2>5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable law or the terms of Slack, Notion, or any connected third-party platform.</li>
              <li>Attempt to gain unauthorized access to the Service, other workspaces&apos; data, or our infrastructure.</li>
              <li>Reverse-engineer, resell, or white-label the Service without our written permission.</li>
            </ul>
          </section>

          <section>
            <h2>6. Third-Party Integrations</h2>
            <p>
              The Service requires you to grant Slack and Notion permissions to function. Your use of Slack
              and Notion remains subject to their own terms of service. We are not responsible for outages,
              API changes, or data loss caused by those third-party platforms.
            </p>
          </section>

          <section>
            <h2>7. AI-Generated Content</h2>
            <p>
              Summaries are generated by third-party AI models (Google Gemini, with Groq as fallback). AI
              output can be inaccurate or incomplete. You are responsible for reviewing generated summaries
              before relying on them as a source of truth.
            </p>
          </section>

          <section>
            <h2>8. Data &amp; Privacy</h2>
            <p>
              Our collection and use of data is governed by our <Link href="/privacy" className="text-foreground underline">Privacy Policy</Link>, incorporated into these Terms by reference.
            </p>
          </section>

          <section>
            <h2>9. Intellectual Property</h2>
            <p>
              The Service, including its software and branding, is owned by Korrali. These Terms do not
              grant you any rights to our intellectual property beyond the ability to use the Service as
              intended. You retain ownership of your own Slack and Notion content.
            </p>
          </section>

          <section>
            <h2>10. Termination</h2>
            <p>
              We may suspend or terminate access to the Service for violation of these Terms or non-payment.
              You may stop using the Service at any time by uninstalling it from Slack and cancelling your
              subscription.
            </p>
          </section>

          <section>
            <h2>11. Disclaimer of Warranties</h2>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of
              any kind, express or implied, including fitness for a particular purpose or non-infringement.
            </p>
          </section>

          <section>
            <h2>12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Korrali will not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Service, and our total
              liability will not exceed the amount you paid us in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2>13. Governing Law</h2>
            <p>
              These Terms are governed by the laws of [jurisdiction to be confirmed], without regard to
              conflict-of-law principles.
            </p>
          </section>

          <section>
            <h2>14. Changes to These Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after a change constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2>15. Contact</h2>
            <p>Questions about these Terms? Email <a href="mailto:hello@korrali.com" className="text-foreground underline">hello@korrali.com</a>.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
